# Generated by Django 4.2.21 on 2025-06-25 10:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aneesapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='registered_at',
            field=models.DateTimeField(),
        ),
    ]
