# Generated by Django 4.2.21 on 2025-06-27 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aneesapp', '0002_event_date_alter_attendee_registered_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='registered_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
