# Generated by Django 4.2.21 on 2025-06-27 11:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aneesapp', '0003_alter_attendee_registered_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.IntegerField(),
        ),
    ]
